web final/final/Controllers/PhuongPhapDieuTriController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using final.Models;

namespace final.Controllers
{
    public class PhuongPhapDieuTriController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /PhuongPhapDieuTri/

        public ActionResult Index()
        {
            return View(db.PPDieuTris.ToList());
        }

        //
        // GET: /PhuongPhapDieuTri/Details/5

        public ActionResult Details(int id = 0)
        {
            PPDieuTri ppdieutri = db.PPDieuTris.Find(id);
            if (ppdieutri == null)
            {
                return HttpNotFound();
            }
            return View(ppdieutri);
        }

        //
        // GET: /PhuongPhapDieuTri/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /PhuongPhapDieuTri/Create

        [HttpPost]
        public ActionResult Create(PPDieuTri ppdieutri)
        {
            if (ModelState.IsValid)
            {
                db.PPDieuTris.Add(ppdieutri);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ppdieutri);
        }

        //
        // GET: /PhuongPhapDieuTri/Edit/5

        public ActionResult Edit(int id = 0)
        {
            PPDieuTri ppdieutri = db.PPDieuTris.Find(id);
            if (ppdieutri == null)
            {
                return HttpNotFound();
            }
            return View(ppdieutri);
        }

        //
        // POST: /PhuongPhapDieuTri/Edit/5

        [HttpPost]
        public ActionResult Edit(PPDieuTri ppdieutri)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ppdieutri).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ppdieutri);
        }

        //
        // GET: /PhuongPhapDieuTri/Delete/5

        public ActionResult Delete(int id = 0)
        {
            PPDieuTri ppdieutri = db.PPDieuTris.Find(id);
            if (ppdieutri == null)
            {
                return HttpNotFound();
            }
            return View(ppdieutri);
        }

        //
        // POST: /PhuongPhapDieuTri/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            PPDieuTri ppdieutri = db.PPDieuTris.Find(id);
            db.PPDieuTris.Remove(ppdieutri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

web final/final/Views/PhuongPhapDieuTri/Create.cshtml
@model final.Models.PPDieuTri

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>PPDieuTri</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.TuaDe)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TuaDe)
            @Html.ValidationMessageFor(model => model.TuaDe)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NoiDung)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HinhAnh)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HinhAnh)
            @Html.ValidationMessageFor(model => model.HinhAnh)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

web final/final/Views/PhuongPhapDieuTri/Delete.cshtml
@model final.Models.PPDieuTri

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>PPDieuTri</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TuaDe)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TuaDe)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NoiDung)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NoiDung)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HinhAnh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HinhAnh)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

web final/final/Views/PhuongPhapDieuTri/Details.cshtml
@model final.Models.PPDieuTri

@{
    ViewBag.Title = "Details";
}

 <div style="padding-left:40px">
        <div class="display-field">
            <h1>@Html.DisplayFor(model => model.TuaDe)</h1>
        </div>

    
        <div class="display-field">
            @Html.DisplayFor(model => model.NoiDung)
        </div>
       </div>

web final/final/Views/PhuongPhapDieuTri/Edit.cshtml
@model final.Models.PPDieuTri

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>PPDieuTri</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.TuaDe)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TuaDe)
            @Html.ValidationMessageFor(model => model.TuaDe)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NoiDung)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoiDung)
            @Html.ValidationMessageFor(model => model.NoiDung)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HinhAnh)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HinhAnh)
            @Html.ValidationMessageFor(model => model.HinhAnh)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

web final/final/Views/PhuongPhapDieuTri/Index.cshtml
@model IEnumerable<final.Models.PPDieuTri>

@{
    ViewBag.Title = "Index";
}

<link href="~/Content/View.css" rel="stylesheet" />

<fieldset>
    <legend>Phương pháp điều trị</legend>
@foreach (var item in Model) {
   
    <div class="module">

       <div class="image">
             <img src="@Url.Content("~/"+item.HinhAnh)" width="100%"  height="100%"/>
         
      </div>
    <div class="content">
        <div>
            <h2>@Html.ActionLink(item.TuaDe, "Details/" + item.ID, "PhuongPhapDieuTri")</h2>
           </div>
        <br />
        
            @Html.DisplayName(item.NoiDung.Substring(0,100))
        </div>
  </div>
}
</fieldset>